#!/bin/bash

curl -X POST 'http://40.78.123.135:8079/api/spark_source/workspaces/saikattstest/execute' \
	-H 'Accept: application/vnd.apache.kylin-v4-public+json' \
	-H 'Accept-Language: en' \
	-H 'Authorization: Basic c2Fpa2F0LmJhc3U6S3lsaWdlbmNlQDIwMjE=' \
	-H 'Content-Type: application/json;charset=utf-8' \
	-d '{ "database":"SSB", \
	"sql":"CREATE VIEW `SSB`.`V_LO_DATE`(`ORDER_KEY`, `LINE_NUMBER`, `ORDER_DATE`, `QUANTITY`, `EXTENDED_PRICE`, `DISCOUNT`, `TOTAL_PRICE`, `REVENUE`, `SUPPLY_COST`, `D_DATE`, `MONTH`, `INT_MONTH`, `YEAR`) AS SELECT SSB.LINEORDER.LO_ORDERKEY AS ORDER_KEY, SSB.LINEORDER.LO_LINENUMBER AS LINE_NUMBER, SSB.LINEORDER.LO_ORDERDATE AS ORDER_DATE, SSB.LINEORDER.LO_QUANTITY AS QUANTITY, SSB.LINEORDER.LO_EXTENDEDPRICE AS EXTENDED_PRICE, SSB.LINEORDER.LO_DISCOUNT AS DISCOUNT, SSB.LINEORDER.LO_ORDTOTALPRICE AS TOTAL_PRICE, SSB.LINEORDER.LO_REVENUE AS REVENUE, SSB.LINEORDER.LO_SUPPLYCOST AS SUPPLYCOST, SSB.DATES.D_DATE AS D_DATE, SSB.DATES.D_MONTH AS D_MONTH, SSB.DATES.D_YEARMONTHNUM AS INT_MONTH, SSB.DATES.D_YEAR AS D_YEAR FROM SSB.LINEORDER JOIN SSB.DATES ON SSB.LINEORDER.LO_ORDERDATE = SSB.DATES.D_DATEKEY" }'

